# scripts/predict/teams.py

# Maps team abbreviation -> (team_id, full_name)
TEAMS = {
    "ANA": (24, "Anaheim Ducks"),
    "BOS": (6, "Boston Bruins"),
    "BUF": (7, "Buffalo Sabres"),
    "CGY": (20, "Calgary Flames"),
    "CAR": (12, "Carolina Hurricanes"),
    "CHI": (16, "Chicago Blackhawks"),
    "COL": (21, "Colorado Avalanche"),
    "CBJ": (29, "Columbus Blue Jackets"),
    "DAL": (25, "Dallas Stars"),
    "DET": (17, "Detroit Red Wings"),
    "EDM": (22, "Edmonton Oilers"),
    "FLA": (13, "Florida Panthers"),
    "LAK": (26, "Los Angeles Kings"),
    "MIN": (30, "Minnesota Wild"),
    "MTL": (8, "Montreal Canadiens"),
    "NSH": (18, "Nashville Predators"),
    "NJD": (1, "New Jersey Devils"),
    "NYI": (2, "New York Islanders"),
    "NYR": (3, "New York Rangers"),
    "OTT": (9, "Ottawa Senators"),
    "PHI": (4, "Philadelphia Flyers"),
    "PIT": (5, "Pittsburgh Penguins"),
    "SJS": (28, "San Jose Sharks"),
    "SEA": (55, "Seattle Kraken"),
    "STL": (19, "St. Louis Blues"),
    "TBL": (14, "Tampa Bay Lightning"),
    "TOR": (10, "Toronto Maple Leafs"),
    "UTA": (59, "Utah Hockey Club"),
    "VAN": (23, "Vancouver Canucks"),
    "VGK": (54, "Vegas Golden Knights"),
    "WSH": (15, "Washington Capitals"),
    "WPG": (52, "Winnipeg Jets"),
}